name : Deploy to ECS

# setting up trigger event
on : 
  push :
    branches : [main]
  pull_request :
    branches: [main]

jobs :

  Build-and-push-to-Ecr :
    runs-on : ubuntu-latest
    steps : 
    - uses: actions/checkout@v2

    - name: connecting to aws cli
      run: |
        aws ecr describe-repositories --region ap-southeast-2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-south-1'

    
