name : Deploy to ECS

# setting up trigger event
on : 
  push :
    branches : [main]
  pull_request :
    branches: [main]

jobs :

  Build-and-push-to-Ecr :
    runs-on : ubuntu-latest
    steps : 
    - uses: actions/checkout@v2

    - name: connecting to aws cli
      run: |
        aws ecr describe-repositories --output text
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-southeast-2'
    - name : build and push image to ecr
      run : | 
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/t4o7l9s3
        docker build -t docker-images .
        docker tag docker-images:latest public.ecr.aws/t4o7l9s3/docker-images:latest
        docker push public.ecr.aws/t4o7l9s3/docker-images:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-southeast-2'
    
