name : Deploy to ECS

# setting up trigger event
on : 
  push :
    branches : [main]
  pull_request :
    branches: [main]

jobs :

  Build-and-push-to-Ecr :
    runs-on : ubuntu-latest
    steps : 
    - uses: actions/checkout@v2

    - name: connecting to aws cli
      run: |
        aws ecr describe-repositories --output text
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-southeast-2'
    - name : build and push image to ecr
      run : | 
        aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 637423357919.dkr.ecr.ap-southeast-2.amazonaws.com
        docker build -t docker-images .
        docker tag docker-images:latest 637423357919.dkr.ecr.ap-southeast-2.amazonaws.com/docker-images:latest
        docker push 637423357919.dkr.ecr.ap-southeast-2.amazonaws.com/docker-images:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-southeast-2'
    
